kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels: 
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30060
  externalIPs:
  - 10.50.1.60
