apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: nginx.34.105.24.28.xip.io
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 80